version: '3.8'

services:
  redis:
    image: redis:alpine

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  web:
    image: ghcr.io/archanium/webwhiz/nodejs:latest
    build: .
    command: node dist/main.js
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb

  nodejs_worker:
    image: ghcr.io/archanium/webwhiz/nodejs:latest
    build: .
    command: node dist/crawler.main.js
    depends_on:
      - redis
      - mongodb

  python_worker:
    image: ghcr.io/archanium/webwhiz/python-worker:latest
    build: ./workers
    depends_on:
      - redis
      - mongodb

  frontend:
    image: ghcr.io/archanium/webwhiz/frontend:latest
    build: ./frontend
    ports:
      - "3030:80"
    depends_on:
      - web

  widget:
    image: ghcr.io/archanium/webwhiz/widget:latest
    build: ./widget
    ports:
      - "3031:80"
    depends_on:
      - web